#!/bin/sh

# Run initialization scripts in /etc/runit/sysinit.  Exit 
# value of this script is 1 if any of the sysinit scripts
# fails, 0 otherwise.

RETVAL=0

echo "start running system initialization scripts."

for script in /etc/runit/sysinit/*; do
	if [ -x "$script" ]; then
		echo "  $script"
		$script || RETVAL=1
	fi
done

echo "finish running system initialization scripts."

exit $RETVAL

